blank_issues_enabled: false
contact_links:
- name: "ğŸ’¬ Support & Questions - Github Community Support"
  url: https://github.com/zyxkv/paper_plot/discussions
  about: Please ask and answer questions here.
- name: "âš ï¸ Documentation Issues"
  url: https://github.com/zyxkv/paper_plot/issues
  about: Please report issues in our documentation here.
